title: Internationale Weserfahrt
email: gbode@freenet.de
description: >
  Website for basic informations and ongoing news
  in the Internationale Weserfahrt: 425km adventure
  from Hann - Münden to Nordenham.
baseurl: ""
url: http://www.international-weserfahrt.de
github_username:  weserfahrt

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
